config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users

  # TODO: need to guard it with devise to only allow admin users
  namespace :admin do
    authenticate :user do
      mount Sidekiq::Web => '/sidekiq'
    end

    resources :houses
    resources :complex_buildings
    resources :commercial_units
    root to: "houses#index"
  end

  get 'pages/home'

  resources :orders, only: %i(new create)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id           :integer          not null, primary key
#  user_id      :integer          not null
#  buyable_type :string           not null
#  buyable_id   :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :buyable, polymorphic: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_asset, only: %i(new create)

  PROPERTY_WHITE_LIST = {
    'House'           => House,
    'CommercialUnit'  => CommercialUnit,
    'ComplexBuilding' => ComplexBuilding
  }

  def new
  end

  def create
    order = Order.create! user: current_user, buyable: @asset
    BuyPropertyJob.perform_later(order)
    redirect_back fallback_location: root_path, notice: 'Property buying request has been filed. You will get an email for confirmation in a while.'
  end

  private

  def set_asset
    property = PROPERTY_WHITE_LIST[params[:kind]]
    @asset = property.find(params[:id])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_commercial_unit.html.erb
<i class="fas fa-store"></i> Shops:  <%= @asset.shops %>
<br>
<i class="fas fa-home"></i> Area: <%= @asset.sqmt %>sqmt
<br>
<i class="fas fa-car-side"></i> Parking:  <%= @asset.parking %>
<br>

app/views/orders/_complex_building.html.erb
<i class="fas fa-home"></i> Units: <%= @asset.units %>
<br>
<i class="fas fa-home"></i> Area: <%= @asset.sqmt %>sqmt

app/views/orders/_house.html.erb
<i class="fas fa-home"></i> Rooms: <%= @asset.rooms %>
<br>
<i class="fas fa-home"></i> Area: <%= @asset.sqmt %>sqmt
<br>
<i class="fas fa-snowflake"></i> Air Condition: <%= @asset.air_cond %>
<br>
<i class="fas fa-building"></i> Floors:  <%= @asset.floors %>
<br>
<i class="fas fa-building"></i> Last Updated:  <%= @asset.updated_at %>
<br>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/new.html.erb
<%= image_tag url_for(@asset.pictures.first) %>
<div class="card-body">
  <p>
    <i class="fas fa-map"></i> Address: <%= @asset.address %>
    <br>
    <i class="fas fa-building"></i> Type: <%= @asset.class.name.titleize %>
    <br>
    <br>
    <i class="fas fa-money-bill-alt"></i> Price: $<%= @asset.price %>
    <br>
    <%= render "#{@asset.class.name.underscore}" %>
  </p>

</div>
<%= link_to 'Buy', orders_path(kind: params[:kind], id: params[:id]), class: 'btn btn-warning', data: {turbo_method: :post, turbo_confirm: 'Are you Sure You Want to Buy This Property?'} %>