config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users

  # TODO: need to guard it with devise to only allow admin users
  namespace :admin do
    authenticate :user do
      mount Sidekiq::Web => '/sidekiq'
    end

    resources :houses
    resources :complex_buildings
    resources :commercial_units
    root to: "houses#index"
  end

  get 'pages/home'

  resources :orders, only: %i(new create)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/pages/home.html.erb
<h1>Properties</h1>
<main id="home">
  <%= paginate @assets %>
  <div class="row">

    <% @assets.each do |asset| %>
      <div class="col-md-4">
        <div class="card w-100 my-4" style="width: 18rem;">
          <a class="card-body" href="<%= new_order_path(kind: asset.kind, id: asset.id) %>">
            <%= image_tag url_for(asset.pictures.first), class: 'w-100' %>
            <br>
            <br>
            <i class="fas fa-map"></i> Type: <%= asset.address %>
            <br>
            <i class="fas fa-home"></i> Type: <%= asset.kind.titleize %>
            <br>
            <br>
            <p>
              <i class="fas fa-money-bill-alt"></i> Price: $<%= asset.price %>
              <br>
              <% if asset.units.present? %>
                <i class="fas fa-home"></i> Units: <%= asset.units %>
                <br>
              <% end %>
              <% if asset.shops.present? %>
                <i class="fas fa-store"></i> Shops:  <%= asset.shops %>
                <br>
              <% end %>
              <% if asset.floors.present? %>
                <i class="fas fa-building"></i> Floors:  <%= asset.floors %>
                <br>
              <% end %>
              <% if asset.parking.present? %>
                <i class="fas fa-car-side"></i> Parking:  <%= asset.parking %>
                <br>
              <% end %>
              <% if asset.air_cond != nil %>
                <i class="fas fa-snowflake"></i> Air Condition: <%= asset.air_cond %>
                <br>
              <% end %>
            </p>
          </a>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @assets %>
</main>